---
title: "Strategy Tactics Report"
author: "Lukasz Bednarz"
date: "12 July 2016"
output: 
  word_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Development/AllRaid/branches/dev_lukasz.bednarz/Services/Raid.Services.TradingEnhancementEngine/R/reports")
setOption("modifiedOnlySource", TRUE)
source("../analysis_modules/strategy_tactics_report/strategy_tactics_report.r")
source("../models/key_library.r")
library(devEMF)

library(lubridate)

```


## Input Data Range

```{r data_range}

trader   <- 11
query <- dated_twelve_monthly_lookback(11, '2016-06-30')
colnames(query) <- c("TraderID", "start", "end")

```


## Define and Trigger Extended Trades computation

```{r extended_trades, results="hide", message=FALSE, warning=FALSE}
strat.tact.report <- new("StrategyTacticsReport")
strat.tact.report <- dataRequest(strat.tact.report, query)
strat.tact.report <- Process(strat.tact.report)

```


## Plot results
<!--```{r plot_results, dev ='emf', fig.ext = 'emf', fig.width=6.75, out.width='6.75in'}-->
```{r plot_results, dev='emf', fig.ext='emf', dpi = 300, fig.width=6.5,out.width='5in'}
require(devEMF)
plt_list <- getOutputGGPlotList(strat.tact.report)

for (plt in plt_list[setdiff(names(plt_list), "Summary")]) {
  plot(plt)
}

```


## Plot summary
<!--```{r plot_summary, dev ='emf', fig.ext = 'emf', fig.width=6.75, out.width='6.75in'}-->
<!-- # ```{r plot_summary, dev='png', fig.ext='png',dpi = 300, fig.width=13, fig.height= 10,out.width='6.5in', out.height= '5in'} -->
```{r plot_summary, dev='emf', fig.ext='emf',fig.width=13, dpi = 300, fig.height= 13, out.width='6.5in', out.height= '6.5in'}

grid.arrange(plt_list$Summary)
```


# 