---
title: "Risk Review Report"
author: "Lukasz Bednarz"
date: "21 July 2016"
output: 
  word_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(TE.Report)
library(devEMF)

library(lubridate)

fig_type <- 'png'

```


## Define Queries

```{r data_range, results='hide', warning=FALSE, message=FALSE}

trader   <- 11
query.js <- dated_eighteen_monthly_lookback(trader, '2016-07-01')
colnames(query.js) <- c("TraderID", "start", "end")

trader   <- 70
query.ba <- dated_eighteen_monthly_lookback(trader, '2016-07-01')
colnames(query.ba) <- c("TraderID", "start", "end")


trader   <- 101
query.dk <- dated_eighteen_monthly_lookback(trader, '2016-07-01')
colnames(query.dk) <- c("TraderID", "start", "end")

```


## Trigger Report Computation

```{r extended_trades, results="hide", message=FALSE, warning=FALSE}
report.js <- new("RiskReviewReport")
report.js <- dataRequest(report.js, query.js)
report.js <- Process(report.js)

report.ba <- new("RiskReviewReport")
report.ba <- dataRequest(report.ba, query.ba)
report.ba <- Process(report.ba)

report.dk <- new("RiskReviewReport")
report.dk <- dataRequest(report.dk, query.dk)
report.dk <- Process(report.dk)

```


## Risk Plots
#BA
```{r plot_focus_ba, dev=fig_type, fig.ext=fig_type, dpi = 300, fig.width=13, fig.height=15}
plt_list <- getOutputGGPlotList(report.ba)

for (plot in plt_list) {
  plot(plot)
}
```

#DK
```{r plot_focus_dk, dev=fig_type, fig.ext=fig_type, dpi = 300, fig.width=13, fig.height=15}
plt_list <- getOutputGGPlotList(report.dk)

for (plot in plt_list) {
  plot(plot)
}
```

#JS
```{r plot_focus_js, dev=fig_type, fig.ext=fig_type, dpi = 300, fig.width=13, fig.height=15}
plt_list <- getOutputGGPlotList(report.js)

for (plot in plt_list) {
  plot(plot)
}
```

