---
title: "Position Revisits Report"
author: "Lukasz Bednarz"
date: "06 July 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Development/AllRaid/branches/dev_lukasz.bednarz/Services/Raid.Services.TradingEnhancementEngine/R/reports")
setOption("modifiedOnlySource", FALSE)
source("../analysis_modules/position_revisits/position_revisits.r")
source("../models/key_library.r")
library(devEMF)

library(lubridate)

```


## Input Data Range

```{r data_range}

trader   <- 11
query <- dated_twelve_monthly_lookback(trader, today())
colnames(query) <- c("TraderID", "start", "end")

```


## Define and Trigger Extended Trades computation

```{r extended_trades, results="hide",  message=FALSE}
pos.rev.an <- new("PositionRevisitsDeltaPrevQuarterAnalysisBlock")
pos.rev.an <- dataRequest(pos.rev.an, query)
pos.rev.an <- Process(pos.rev.an)

```


## Plot results
```{r plot_results, dev ='emf', fig.ext = 'emf'}


plt_list <- getOutputGGPlot(pos.rev.an)


plot(plt_list)
```



# 